version: "3.3"
services:
  mongodb:
    container_name: "mongodb2"
    hostname: mongodb2
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data2/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root2
      MONGO_INITDB_ROOT_PASSWORD: example2
      MONGO_INITDB_DATABASE: tasks2
  backend:
    build: ./backend/task-manager-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  frontend:
    build: ./frontend/task-manager
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mongo_data: