version: "3.3"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  backend:
    build: ./backend/task-manager-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  frontend:
    build: ./frontend/task-manager
    ports:
      - "4200:80"
    depends_on:
      - backend
